/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:98de309b-7be9-4e89-87b6-fa2562f30518",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_CbMv2ye6I",
    "aws_user_pools_web_client_id": "1s3gn4jic6p47vtifu9nhj0oaf",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://v22e5s3v4na7lawkbprfxotigq.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-6hxueqrgprabhgs4uj25fhevbq",
    "aws_user_files_s3_bucket": "uboostsphotos151451-dev",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;
